---
name: Checks

on:
  push:
  pull_request:

jobs:
  checks:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - name: aarch64-linux
            runs-on: ubuntu-24.04-arm
          - name: aarch64-darwin
            runs-on: macos-15
          - name: x86_64-linux
            runs-on: ubuntu-24.04
          - name: x86_64-darwin
            runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Flake Check
        run: nix flake check

      - name: Check Formatting
        run: nix fmt -- --ci
